name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configurer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Exécuter les tests unitaires
      run: |
        python -m unittest discover tests
    - name: Vérifier la qualité du code avec Flake8
      run: |
          flake8 .
    - name: Analyser le code pour les vulnérabilités avec Bandit
      run: |
          bandit -r .
          - name: Construire l'image Docker
          run: |
            docker build -t fintech-app .
            - name: Connexion à Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          
          - name: Construire et pousser l'image Docker
            run: |
              docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fintech-app:${{ github.sha }} .
              docker push ${{ secrets.DOCKERHUB_USERNAME }}/fintech-app:${{ github.sha }}
                    
                  
      